# Generated by Django 5.1.5 on 2025-02-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=20)),
                ('class_days', models.TextField()),
                ('class_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('billing_method', models.CharField(choices=[('aula', 'Aula'), ('mensal', 'Mensal')], max_length=10)),
                ('class_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('phone_number', models.CharField(blank=True, default=' ', max_length=15, null=True)),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('I', 'I'), ('PRO', 'PRO')], max_length=3)),
                ('due_date', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Parou', 'Parou'), ('Novo', 'Novo'), ('Retornou', 'Retornou')], max_length=50, null=True)),
                ('status_payment', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_att', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': [models.Case(models.When(status='Parou', then=models.Value(4)), models.When(status='Retornou', then=models.Value(3)), models.When(status='Novo', then=models.Value(2)), models.When(status='Regular', then=models.Value(1)), default=models.Value(5), output_field=models.IntegerField())],
            },
        ),
    ]
